import sys

args = sys.argv

if len(args) < 3:
	print("Not enough args", file=sys.stderr)
	sys.exit(1)
	
configh = args[1]
includeh = args[2]

with open(configh, "rt") as f:
	configh = f.read()
	
with open(includeh, "rt") as f:
	includeh = f.read()
	

includeh = includeh.replace('#include "config.h"', configh)

print(f"//=========================================================")
print(f"// THIS FILE WAS AUTOGENERATED FROM {args[1]} and {args[2]}")
print(f"//=========================================================")
print(includeh)
